### ISSUE TITLE
静态图转动态图后权重大小变大

### ISSUE THREAD

**Issue by morgan-bc** [LKKlein/PaddleTools#2]
静态图转动态图后，动态图权重字节数变大，比如 vgg16本应该是 527MB，转为动态图后大小变为795MB，这中间有什么问题吗？转换前后权重所占字节数不应该是差不多吗？

**Comment by LKKlein** [comment]
静态图和动态图参数存储的方式不同，静态图是直接存储的二进制数据，而动态图则保存了PaddlePaddle变量的数据结构，而且存储也是使用Python的Pickle进行存储的，所以参数文件大小会大很多。有关动态图的参数存储可以看官方源码：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/dygraph/checkpoint.py

另外，Paddle最新更新为存储numpy矩阵，文件大小可能会稍小一些，近期会抽时间更新一下。

**Comment by suishicity** [comment]
还是不对，你这个保存的权重结果读出来重新赋值将 vgg 的 fc6的大小改变了，我将转换后的权重赋值给动态图，报错如下：
`Variable Shape not match, Variable [ fc6_weights ] need tensor with shape (512, 4096) but load set tensor with shape (25088, 4096)`
